### ISSUE TITLE
ETQ invité j'accepte l'invitation à rejoindre un voyage

### ISSUE THREAD

**Issue by MathieuFV** [MathieuFV/gathergo#4]
Géré par post /trips/trip[:id]/participations/create sur participationsController#create

**Comment by MathieuFV** [comment]
Géré par post /trips/trip[:id]/participations/ sur participationsController#create

**Comment by MarinB-56** [comment]
Pas de controller **PARTICIPATION**

Donc l'acceptation de l'invitation passe directement par une action du controller **TRIP**.
Redirige effectivement vers GET /trips/:id/show sur tripsController#show
